name: Build Binaries

on: [push]

jobs:
  release:
    name: Build and Release
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Linux amd64
        run: go build -v -o bin/qcg-installer-linux-amd64

      - name: Build Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -v -o bin/qcg-installer-windows-amd64.exe

      - name: Release Binaries
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
