name: Go Build and Release

on:
  push:
    paths:
      - '**.go'
  pull_request:
    types:
      - closed
    paths:
      - '**.go'
    branches:
      - master

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Enable Go Module111 and Go mod Tidy
      run: |
        go mod download
        go mod tidy

    - name: Build Windows x64
      run: |
        GOOS=windows GOARCH=amd64 go build -o qcg-installer-windows-amd64.exe

    - name: Build Linux x64
      run: |
        GOOS=linux GOARCH=amd64 go build -o qcg-installer-linux-amd64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: auto-release-${{ github.sha }}
        release_name: qcg-install Auto Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Windows x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./qcg-installer-windows-amd64.exe
        asset_name: qcg-installer-windows-amd64.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./qcg-installer-linux-amd64
        asset_name: qcg-installer-linux-amd64
        asset_content_type: application/octet-stream
