name: Build Linux amd64

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -o bin/qcg-installer-linux-amd64

      - name: Release Binarys
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/qcg-installer-linux-amd64"
          token: ${{ secrets.MY_GITHUB_TOKEN }}